[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --partition-table=./partitions.csv -s 16mb --monitor --chip esp32s3 -B 921600"

[env]

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
